"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  Activity, ArrowUpRight, Bell, CalendarDays, Check, ChevronRight, CircleUserRound,
  Clock3, CreditCard, Dumbbell, Flame, Home, Info, LineChart, MessageCircle, Play,
  Plus, Search, ShieldCheck, Sparkles, TrendingUp, UserRoundPlus, UsersRound, WalletCards,
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Toaster } from "@/components/ui/sonner";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Role = "member" | "trainer" | "admin";
type View = "home" | "routine" | "progress" | "people";

const exercises = [
  { name: "Press banca", detail: "4 series · 8–10 reps", weight: "62,5 kg", muscle: "Pecho", cue: "Escápulas juntas, pies firmes y bajá la barra al centro del pecho.", rest: "2 min" },
  { name: "Press inclinado", detail: "3 series · 10 reps", weight: "22 kg", muscle: "Pecho superior", cue: "Banco a 30°, muñecas neutras y recorrido controlado.", rest: "90 s" },
  { name: "Aperturas en polea", detail: "3 series · 12 reps", weight: "17,5 kg", muscle: "Pectoral", cue: "Codos apenas flexionados; juntá las manos sin encoger hombros.", rest: "60 s" },
  { name: "Extensión de tríceps", detail: "3 series · 12–15 reps", weight: "25 kg", muscle: "Tríceps", cue: "Pegá los codos al cuerpo y extendé sin mover los hombros.", rest: "60 s" },
];

const clients = [
  { name: "Martina López", plan: "Fuerza inicial", next: "Hoy", streak: 12, status: "Al día", initials: "ML" },
  { name: "Tomás Benítez", plan: "Hipertrofia 4D", next: "Mañana", streak: 7, status: "Revisar", initials: "TB" },
  { name: "Sofía Álvarez", plan: "Full body", next: "Hoy", streak: 18, status: "Al día", initials: "SA" },
  { name: "Nicolás Ruiz", plan: "Sin rutina", next: "—", streak: 2, status: "Asignar", initials: "NR" },
];

const expiringMembers = [
  { name: "Camila Torres", plan: "Mensual", days: 1, amount: "$35.000" },
  { name: "Franco Medina", plan: "Trimestral", days: 3, amount: "$89.000" },
  { name: "Valentina Paz", plan: "Mensual", days: 5, amount: "$35.000" },
];

export default function GymSpotterApp() {
  const [role, setRole] = useState<Role>("member");
  const [view, setView] = useState<View>("home");
  const [completed, setCompleted] = useState<number[]>([0]);
  const [workoutActive, setWorkoutActive] = useState(false);
  const [selectedExercise, setSelectedExercise] = useState<number | null>(null);
  const [assignOpen, setAssignOpen] = useState(false);
  const [selectedClient, setSelectedClient] = useState("Nicolás Ruiz");
  const [selectedPlan, setSelectedPlan] = useState("Hipertrofia 4 días");

  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool?: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    const register = async () => {
      await context.registerTool?.({
        name: "start_today_workout",
        title: "Iniciar entrenamiento",
        description: "Inicia la rutina de pecho y tríceps de hoy en GymSpotter.",
        inputSchema: { type: "object", properties: {}, additionalProperties: false },
        annotations: { readOnlyHint: false, untrustedContentHint: false },
        execute: async () => { setRole("member"); setView("home"); setWorkoutActive(true); return { status: "started", routine: "Pecho + tríceps" }; },
      }, { signal: lifecycle.signal });
      await context.registerTool?.({
        name: "assign_training_plan",
        title: "Asignar rutina",
        description: "Asigna una rutina disponible a un alumno del entrenador.",
        inputSchema: { type: "object", properties: { client: { type: "string", enum: clients.map((client) => client.name) }, plan: { type: "string", enum: ["Hipertrofia 4 días", "Fuerza inicial", "Full body 3 días"] } }, required: ["client", "plan"], additionalProperties: false },
        annotations: { readOnlyHint: false, untrustedContentHint: false },
        execute: async (input: unknown) => { const data = input as { client?: string; plan?: string }; if (!data.client || !data.plan) throw new Error("Alumno y rutina son obligatorios"); setSelectedClient(data.client); setSelectedPlan(data.plan); setRole("trainer"); setView("people"); return { status: "assigned", client: data.client, plan: data.plan }; },
      }, { signal: lifecycle.signal });
    };
    void register().catch(() => undefined);
    return () => lifecycle.abort();
  }, []);

  const roleLabel = role === "member" ? "Socio" : role === "trainer" ? "Entrenador" : "Administrador";
  const displayName = role === "member" ? "Lucas" : role === "trainer" ? "Mateo" : "Club Central";

  function changeRole(next: Role) { setRole(next); setView("home"); }
  function completeExercise(index: number) {
    setCompleted((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index]);
    setSelectedExercise(null);
    toast.success(completed.includes(index) ? "Ejercicio marcado como pendiente" : "Ejercicio completado");
  }

  return (
    <main className="min-h-screen bg-[#090b0a] pb-24 text-[#f3f4ee] lg:pb-0">
      <Toaster position="top-center" richColors />
      <AppHeader role={role} roleLabel={roleLabel} displayName={displayName} onRoleChange={changeRole} />
      <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[200px_minmax(0,1fr)] lg:py-8">
        <Sidebar role={role} view={view} onView={setView} />
        <section className="min-w-0">
          {role === "member" && <MemberArea view={view} completed={completed} workoutActive={workoutActive} setWorkoutActive={setWorkoutActive} setSelectedExercise={setSelectedExercise} onView={setView} />}
          {role === "trainer" && <TrainerArea view={view} onAssign={() => setAssignOpen(true)} />}
          {role === "admin" && <AdminArea view={view} />}
        </section>
      </div>
      <MobileNav role={role} view={view} onView={setView} />

      <Dialog open={selectedExercise !== null} onOpenChange={(open) => !open && setSelectedExercise(null)}>
        <DialogContent className="border-white/10 bg-[#171a17] text-white sm:max-w-md">
          {selectedExercise !== null && <><DialogHeader><div className="mb-2 grid size-12 place-items-center rounded-2xl bg-[#c7ff3d]/10 text-[#c7ff3d]"><Dumbbell /></div><DialogTitle className="text-2xl font-black">{exercises[selectedExercise].name}</DialogTitle><DialogDescription className="text-white/50">{exercises[selectedExercise].muscle} · Descanso {exercises[selectedExercise].rest}</DialogDescription></DialogHeader><div className="rounded-xl border border-white/10 bg-white/5 p-4"><p className="mb-1 text-xs font-bold uppercase tracking-wider text-[#c7ff3d]">Técnica</p><p className="text-sm leading-6 text-white/70">{exercises[selectedExercise].cue}</p></div><div className="grid grid-cols-2 gap-3"><StatMini label="Objetivo" value={exercises[selectedExercise].detail.replace(" series ·", " ×")} /><StatMini label="Peso anterior" value={exercises[selectedExercise].weight} /></div><DialogFooter><Button variant="outline" onClick={() => setSelectedExercise(null)} className="border-white/15 bg-transparent hover:bg-white/10">Cerrar</Button><Button onClick={() => completeExercise(selectedExercise)} className="bg-[#c7ff3d] font-black text-black hover:bg-[#d5ff6c]">{completed.includes(selectedExercise) ? "Marcar pendiente" : "Completar ejercicio"}</Button></DialogFooter></>}
        </DialogContent>
      </Dialog>

      <Dialog open={assignOpen} onOpenChange={setAssignOpen}>
        <DialogContent className="border-white/10 bg-[#171a17] text-white sm:max-w-md"><DialogHeader><DialogTitle className="text-2xl font-black">Asignar una rutina</DialogTitle><DialogDescription className="text-white/50">El alumno la recibirá inmediatamente en su celular.</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-bold"><span>Alumno</span><Select value={selectedClient} onValueChange={setSelectedClient}><SelectTrigger className="w-full border-white/15 bg-white/5"><SelectValue /></SelectTrigger><SelectContent>{clients.map((client) => <SelectItem key={client.name} value={client.name}>{client.name}</SelectItem>)}</SelectContent></Select></label><label className="space-y-2 text-sm font-bold"><span>Rutina</span><Select value={selectedPlan} onValueChange={setSelectedPlan}><SelectTrigger className="w-full border-white/15 bg-white/5"><SelectValue /></SelectTrigger><SelectContent>{["Hipertrofia 4 días", "Fuerza inicial", "Full body 3 días"].map((plan) => <SelectItem key={plan} value={plan}>{plan}</SelectItem>)}</SelectContent></Select></label><DialogFooter><Button variant="outline" onClick={() => setAssignOpen(false)} className="border-white/15 bg-transparent hover:bg-white/10">Cancelar</Button><Button onClick={() => { setAssignOpen(false); toast.success(`Rutina asignada a ${selectedClient}`); }} className="bg-[#c7ff3d] font-black text-black hover:bg-[#d5ff6c]">Asignar rutina</Button></DialogFooter></DialogContent>
      </Dialog>
    </main>
  );
}

function AppHeader({ role, roleLabel, displayName, onRoleChange }: { role: Role; roleLabel: string; displayName: string; onRoleChange: (role: Role) => void }) {
  return <header className="sticky top-0 z-30 border-b border-white/10 bg-[#090b0a]/90 backdrop-blur-xl"><div className="mx-auto flex min-h-18 max-w-7xl items-center justify-between gap-3 px-4 py-3 sm:px-6"><Brand /><div className="flex items-center gap-2"><Select value={role} onValueChange={(value) => onRoleChange(value as Role)}><SelectTrigger size="sm" aria-label="Cambiar perfil" className="border-white/10 bg-white/5 font-bold text-white"><SelectValue>{roleLabel}</SelectValue></SelectTrigger><SelectContent><SelectItem value="member">Socio</SelectItem><SelectItem value="trainer">Entrenador</SelectItem><SelectItem value="admin">Administrador</SelectItem></SelectContent></Select><Button variant="ghost" size="icon" className="hidden rounded-full text-white/70 hover:bg-white/10 hover:text-white sm:inline-flex" aria-label="Notificaciones"><Bell /></Button><div className="hidden items-center gap-3 rounded-full border border-white/10 bg-white/5 py-1.5 pl-3 pr-1.5 md:flex"><span className="text-sm font-semibold">{displayName}</span><CircleUserRound className="size-7 text-[#c7ff3d]" /></div></div></div></header>;
}

function Brand() { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#c7ff3d] text-[#0a0c0a]"><Dumbbell className="size-5" strokeWidth={2.6} /></div><div><p className="text-lg font-black tracking-[-0.04em]">GYM<span className="text-[#c7ff3d]">SPOTTER</span></p><p className="hidden text-[11px] uppercase tracking-[0.16em] text-white/45 sm:block">Athletic Club</p></div></div>; }

function Sidebar({ role, view, onView }: { role: Role; view: View; onView: (view: View) => void }) {
  const items = role === "member" ? [["home", <Home />, "Inicio"], ["routine", <Dumbbell />, "Mi rutina"], ["progress", <LineChart />, "Progreso"], ["people", <UsersRound />, "Mi entrenador"]] : role === "trainer" ? [["home", <Home />, "Resumen"], ["people", <UsersRound />, "Alumnos"], ["routine", <Dumbbell />, "Rutinas"], ["progress", <LineChart />, "Resultados"]] : [["home", <Home />, "Resumen"], ["people", <UsersRound />, "Socios"], ["routine", <CreditCard />, "Membresías"], ["progress", <LineChart />, "Reportes"]];
  return <aside className="hidden lg:block"><nav className="sticky top-26 space-y-1" aria-label="Navegación principal">{items.map(([key, icon, label]) => <NavItem key={key as string} icon={icon as ReactNode} label={label as string} active={view === key} onClick={() => onView(key as View)} />)}</nav></aside>;
}

function MemberArea({ view, completed, workoutActive, setWorkoutActive, setSelectedExercise, onView }: { view: View; completed: number[]; workoutActive: boolean; setWorkoutActive: (active: boolean) => void; setSelectedExercise: (index: number) => void; onView: (view: View) => void }) {
  if (view === "routine") return <RoutineView completed={completed} setSelectedExercise={setSelectedExercise} />;
  if (view === "progress") return <ProgressView />;
  if (view === "people") return <TrainerContact />;
  return <><PageTitle eyebrow="Viernes 11 de septiembre" title="Hoy toca empujar." accessory={<span className="hidden items-center gap-2 text-sm text-white/45 sm:flex"><Flame className="size-4 text-orange-400" /> 8 semanas activo</span>} /><div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(290px,.8fr)]"><WorkoutCard completed={completed} workoutActive={workoutActive} onStart={() => { setWorkoutActive(true); toast.success("Entrenamiento iniciado"); }} setSelectedExercise={setSelectedExercise} /><div className="space-y-5"><MembershipCard /><WeekCard /><button onClick={() => onView("people")} className="flex w-full items-center gap-4 rounded-[22px] border border-white/10 bg-[#121512] p-4 text-left transition-colors hover:border-[#c7ff3d]/35"><Avatar initials="MG" /><span className="min-w-0 flex-1"><span className="block text-sm font-bold">Mateo, tu entrenador</span><span className="block truncate text-xs text-white/45">Buen trabajo con el press de hoy</span></span><MessageCircle className="size-5 text-[#c7ff3d]" /></button></div></div></>;
}

function WorkoutCard({ completed, workoutActive, onStart, setSelectedExercise }: { completed: number[]; workoutActive: boolean; onStart: () => void; setSelectedExercise: (index: number) => void }) {
  const percent = Math.round(completed.length / exercises.length * 100);
  return <article className="overflow-hidden rounded-[26px] border border-white/10 bg-[#121512]"><div className="flex items-start justify-between gap-3 border-b border-white/10 p-5 sm:p-6"><div><span className="rounded-full bg-[#c7ff3d]/12 px-3 py-1 text-xs font-bold uppercase tracking-[0.13em] text-[#c7ff3d]">Entrenamiento de hoy</span><h2 className="mt-4 text-2xl font-black tracking-tight">Pecho + tríceps</h2><p className="mt-1 flex items-center gap-2 text-sm text-white/50"><Clock3 className="size-4" /> 55 min · {exercises.length} ejercicios</p></div><div className="grid size-14 place-items-center rounded-2xl border border-[#c7ff3d]/30 bg-[#c7ff3d]/10 text-[#c7ff3d]"><Dumbbell className="size-6" /></div></div>{workoutActive && <div className="px-5 pt-5 sm:px-6"><div className="mb-2 flex justify-between text-xs font-bold"><span>Progreso actual</span><span className="text-[#c7ff3d]">{percent}%</span></div><Progress value={percent} className="bg-white/10" /></div>}<div className="divide-y divide-white/8 px-5 sm:px-6">{exercises.map((exercise, index) => <button key={exercise.name} onClick={() => setSelectedExercise(index)} className="group flex w-full items-center gap-4 py-4 text-left"><span className={`grid size-8 shrink-0 place-items-center rounded-full text-sm font-black ${completed.includes(index) ? "bg-[#c7ff3d] text-black" : "border border-white/15 text-white/45"}`}>{completed.includes(index) ? <Check className="size-4" /> : index + 1}</span><span className="min-w-0 flex-1"><span className="block truncate font-bold">{exercise.name}</span><span className="mt-0.5 block text-sm text-white/45">{exercise.detail}</span></span><span className="hidden text-right sm:block"><span className="block text-sm font-bold">{exercise.weight}</span><span className="block text-xs text-white/35">última vez</span></span><ChevronRight className="size-4 text-white/25 transition-transform group-hover:translate-x-1" /></button>)}</div><div className="p-5 pt-2 sm:p-6 sm:pt-3"><Button onClick={onStart} className="h-13 w-full rounded-xl bg-[#c7ff3d] text-base font-black text-black hover:bg-[#d3ff67]"><Play className="fill-current" /> {workoutActive ? "Continuar entrenamiento" : "Empezar entrenamiento"}</Button></div></article>;
}

function MembershipCard() { return <article className="rounded-[26px] bg-[#c7ff3d] p-5 text-[#11140e] sm:p-6"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[0.14em]">Membresía activa</span><span className="size-2 rounded-full bg-[#11140e]" /></div><p className="mt-8 text-5xl font-black tracking-[-0.06em]">12</p><p className="font-bold">días restantes</p><Progress value={62} className="mt-5 bg-black/15 [&>div]:bg-black" /><div className="mt-3 flex justify-between text-xs font-bold text-black/55"><span>Plan mensual</span><span>Vence 23 sep</span></div><Button onClick={() => toast.success("Solicitud de renovación enviada")} className="mt-5 w-full bg-black font-bold text-white hover:bg-black/80">Renovar membresía</Button></article>; }
function WeekCard() { return <article className="rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-white/40">Esta semana</p><div className="mt-4 flex items-end justify-between gap-2"><div><span className="text-4xl font-black">3</span><span className="ml-1 text-white/40">/ 4</span><p className="mt-1 text-sm text-white/50">entrenamientos</p></div><MiniBars /></div></article>; }

function RoutineView({ completed, setSelectedExercise }: { completed: number[]; setSelectedExercise: (index: number) => void }) { return <><PageTitle eyebrow="Plan asignado por Mateo" title="Mi rutina semanal" /><div className="mb-5 flex gap-2 overflow-x-auto pb-2">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map((day, index) => <button key={day} className={`min-w-16 rounded-2xl border px-3 py-3 text-center ${index === 4 ? "border-[#c7ff3d] bg-[#c7ff3d] text-black" : "border-white/10 bg-[#121512] text-white/45"}`}><span className="block text-xs font-bold">{day}</span><span className="mt-1 block text-lg font-black">{7 + index}</span></button>)}</div><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-bold text-[#c7ff3d]">Día 4</p><h2 className="text-2xl font-black">Pecho + tríceps</h2></div><span className="text-sm text-white/45">55 min</span></div><div className="space-y-3">{exercises.map((exercise, index) => <button key={exercise.name} onClick={() => setSelectedExercise(index)} className="flex w-full items-center gap-4 rounded-2xl border border-white/8 bg-white/[.025] p-4 text-left hover:border-[#c7ff3d]/30"><span className={`grid size-9 shrink-0 place-items-center rounded-xl font-black ${completed.includes(index) ? "bg-[#c7ff3d] text-black" : "bg-white/5 text-white/45"}`}>{completed.includes(index) ? <Check className="size-4" /> : index + 1}</span><span className="min-w-0 flex-1"><span className="block font-bold">{exercise.name}</span><span className="text-sm text-white/40">{exercise.detail}</span></span><Info className="size-4 text-white/30" /></button>)}</div></article><article className="h-fit rounded-[26px] border border-white/10 bg-[#121512] p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Próximo entrenamiento</p><p className="mt-4 text-xl font-black">Espalda + bíceps</p><p className="mt-1 text-sm text-white/45">Lunes · 6 ejercicios</p><div className="mt-6 rounded-xl bg-[#c7ff3d]/10 p-4 text-sm leading-6 text-[#dfff91]">Mateo ajustó los remos a 4 series para esta semana.</div></article></div></>; }

function ProgressView() { return <><PageTitle eyebrow="Últimos 90 días" title="Tu progreso" accessory={<Button variant="outline" className="border-white/15 bg-white/5 hover:bg-white/10"><CalendarDays /> Cambiar período</Button>} /><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Entrenamientos" value="42" change="+12%" /><MetricCard label="Volumen total" value="184k" suffix="kg" change="+8%" /><MetricCard label="Récords personales" value="7" change="Este mes" /></div><article className="mt-5 rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-white/45">Press banca</p><h2 className="text-2xl font-black">Estimación de fuerza</h2></div><div className="text-right"><p className="text-2xl font-black text-[#c7ff3d]">78 kg</p><p className="text-xs text-white/40">1RM estimado</p></div></div><ProgressChart /></article><div className="mt-5 grid gap-5 md:grid-cols-2"><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Constancia</p><div className="mt-4 flex items-center gap-4"><div className="grid size-16 place-items-center rounded-2xl bg-orange-400/10 text-orange-400"><Flame className="size-8" /></div><div><p className="text-3xl font-black">8 semanas</p><p className="text-sm text-white/45">Tu mejor racha hasta ahora</p></div></div></article><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Peso corporal</p><div className="mt-4 flex items-end justify-between"><div><p className="text-3xl font-black">78,4 kg</p><p className="text-sm text-white/45">−1,8 kg desde junio</p></div><TrendingUp className="size-7 text-[#c7ff3d]" /></div></article></div></>; }

function TrainerContact() { return <><PageTitle eyebrow="Acompañamiento personal" title="Tu entrenador" /><div className="grid gap-5 lg:grid-cols-[1fr_340px]"><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Avatar initials="MG" large /><div className="flex-1"><p className="text-2xl font-black">Mateo González</p><p className="mt-1 text-white/45">Entrenador de fuerza e hipertrofia</p><div className="mt-3 flex gap-2"><Pill>4,9 ★</Pill><Pill>8 años de experiencia</Pill></div></div><Button onClick={() => toast.success("Mensaje enviado a Mateo")} className="bg-[#c7ff3d] font-black text-black"><MessageCircle /> Escribirle</Button></div><div className="mt-7 rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#c7ff3d]">Último comentario</p><p className="mt-3 leading-7 text-white/75">“Muy buen control en el press. Hoy mantené 62,5 kg y buscá completar las cuatro series con técnica limpia.”</p><p className="mt-3 text-xs text-white/35">Ayer, 18:42</p></div></article><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Próxima revisión</p><p className="mt-4 text-4xl font-black">18 SEP</p><p className="mt-2 text-sm text-white/50">Medidas, técnica y ajuste de cargas</p><Button variant="outline" onClick={() => toast.success("Recordatorio agendado")} className="mt-6 w-full border-white/15 bg-white/5 hover:bg-white/10"><Bell /> Recordarme</Button></article></div></>; }

function TrainerArea({ view, onAssign }: { view: View; onAssign: () => void }) {
  if (view === "people") return <><PageTitle eyebrow="Cartera activa" title="Mis alumnos" accessory={<Button onClick={onAssign} className="bg-[#c7ff3d] font-black text-black"><Plus /> Asignar rutina</Button>} /><ClientList /></>;
  if (view === "routine") return <RoutineLibrary onAssign={onAssign} />;
  if (view === "progress") return <TrainerResults />;
  return <><PageTitle eyebrow="Panel del entrenador" title="Buen día, Mateo." accessory={<Button onClick={onAssign} className="bg-[#c7ff3d] font-black text-black"><Plus /> Asignar rutina</Button>} /><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Alumnos activos" value="24" change="+3 este mes" /><MetricCard label="Entrenan hoy" value="9" change="6 completaron" /><MetricCard label="Para revisar" value="4" change="Requieren atención" alert /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.75fr]"><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-white/40">Seguimiento</p><h2 className="mt-1 text-xl font-black">Actividad reciente</h2></div><Button variant="ghost" size="sm" className="text-[#c7ff3d]">Ver todos <ChevronRight /></Button></div><ClientList compact /></article><article className="rounded-[26px] bg-[#c7ff3d] p-5 text-black sm:p-6"><Sparkles className="size-8" /><h2 className="mt-6 text-2xl font-black">4 alumnos necesitan un ajuste.</h2><p className="mt-2 text-sm leading-6 text-black/65">Detectamos cargas estancadas o rutinas sin actualizar hace más de seis semanas.</p><Button onClick={() => toast.info("Revisión de alumnos abierta")} className="mt-7 w-full bg-black font-bold text-white">Revisar ahora</Button></article></div></>;
}

function ClientList({ compact = false }: { compact?: boolean }) { const shown = compact ? clients.slice(0, 3) : clients; return <div className={compact ? "divide-y divide-white/8" : "grid gap-3"}>{shown.map((client) => <button key={client.name} onClick={() => toast.info(`Perfil de ${client.name}`)} className={`flex w-full items-center gap-4 text-left ${compact ? "py-4" : "rounded-2xl border border-white/10 bg-[#121512] p-4 hover:border-[#c7ff3d]/30"}`}><Avatar initials={client.initials} /><span className="min-w-0 flex-1"><span className="block font-bold">{client.name}</span><span className="text-sm text-white/40">{client.plan} · Próximo: {client.next}</span></span><span className="hidden text-right sm:block"><span className="block text-sm font-bold">{client.streak} sesiones</span><span className={`text-xs ${client.status === "Al día" ? "text-[#c7ff3d]" : "text-amber-400"}`}>{client.status}</span></span><ChevronRight className="size-4 text-white/25" /></button>)}</div>; }

function RoutineLibrary({ onAssign }: { onAssign: () => void }) { return <><PageTitle eyebrow="Plantillas reutilizables" title="Biblioteca de rutinas" accessory={<Button onClick={() => toast.info("Editor de rutina preparado")} className="bg-[#c7ff3d] font-black text-black"><Plus /> Nueva rutina</Button>} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["Hipertrofia 4 días", "Intermedio", "4 días · 22 ejercicios"], ["Fuerza inicial", "Principiante", "3 días · 15 ejercicios"], ["Full body 3 días", "General", "3 días · 18 ejercicios"]].map(([name, level, detail], index) => <article key={name} className="rounded-[24px] border border-white/10 bg-[#121512] p-5"><div className="flex items-center justify-between"><div className="grid size-11 place-items-center rounded-xl bg-[#c7ff3d]/10 text-[#c7ff3d]"><Dumbbell /></div><span className="text-xs font-bold uppercase tracking-wider text-white/35">{level}</span></div><h2 className="mt-7 text-xl font-black">{name}</h2><p className="mt-1 text-sm text-white/45">{detail}</p><div className="mt-6 flex gap-2"><Button onClick={onAssign} className="flex-1 bg-[#c7ff3d] font-bold text-black">Asignar</Button><Button variant="outline" onClick={() => toast.info(`Editando ${name}`)} className="border-white/15 bg-transparent">Editar</Button></div></article>)}</div></>; }

function TrainerResults() { return <><PageTitle eyebrow="Todos tus alumnos" title="Resultados del equipo" /><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Adherencia promedio" value="82" suffix="%" change="+6%" /><MetricCard label="Sesiones este mes" value="218" change="+24" /><MetricCard label="Récords logrados" value="39" change="Últimos 30 días" /></div><article className="mt-5 rounded-[26px] border border-white/10 bg-[#121512] p-6"><h2 className="text-xl font-black">Adherencia semanal</h2><ProgressChart /></article></>; }

function AdminArea({ view }: { view: View }) {
  if (view === "people") return <><PageTitle eyebrow="Base de socios" title="Socios activos" accessory={<Button onClick={() => toast.info("Alta de socio preparada")} className="bg-[#c7ff3d] font-black text-black"><UserRoundPlus /> Nuevo socio</Button>} /><div className="mb-4 flex items-center gap-3 rounded-xl border border-white/10 bg-[#121512] px-4 py-3"><Search className="size-4 text-white/35" /><input aria-label="Buscar socio" placeholder="Buscar por nombre o documento" className="w-full bg-transparent text-sm outline-none placeholder:text-white/30" /></div><ClientList /></>;
  if (view === "routine") return <MembershipsView />;
  if (view === "progress") return <AdminReports />;
  return <><PageTitle eyebrow="Gestión del gimnasio" title="Todo bajo control." accessory={<Button onClick={() => toast.info("Alta de socio preparada")} className="bg-[#c7ff3d] font-black text-black"><UserRoundPlus /> Nuevo socio</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Socios activos" value="428" change="+18 este mes" /><MetricCard label="Ingresos del mes" value="$14,8M" change="+9,2%" /><MetricCard label="Vencen esta semana" value="23" change="Contactar hoy" alert /><MetricCard label="En el gimnasio" value="67" change="Ahora mismo" /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.8fr]"><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-white/40">Renovaciones</p><h2 className="mt-1 text-xl font-black">Próximos vencimientos</h2></div><span className="text-sm font-bold text-[#c7ff3d]">23 esta semana</span></div><ExpiringList /></article><article className="rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-white/40">Ocupación de hoy</p><h2 className="mt-1 text-xl font-black">Hora por hora</h2><div className="mt-8 flex h-40 items-end justify-between gap-2">{[18, 32, 68, 92, 76, 58, 84, 100, 72, 42].map((height, index) => <div key={index} className="group flex h-full flex-1 items-end"><span className={`w-full rounded-t-md ${index === 7 ? "bg-[#c7ff3d]" : "bg-white/10 group-hover:bg-white/20"}`} style={{ height: `${height}%` }} /></div>)}</div><div className="mt-3 flex justify-between text-xs text-white/30"><span>07 h</span><span>12 h</span><span>17 h</span><span>22 h</span></div></article></div></>;
}

function ExpiringList() { return <div className="divide-y divide-white/8">{expiringMembers.map((member) => <div key={member.name} className="flex items-center gap-3 py-4"><Avatar initials={member.name.split(" ").map((part) => part[0]).join("")} /><span className="min-w-0 flex-1"><span className="block font-bold">{member.name}</span><span className="text-sm text-white/40">{member.plan} · vence en {member.days} {member.days === 1 ? "día" : "días"}</span></span><span className="font-bold">{member.amount}</span><Button onClick={() => toast.success(`Aviso enviado a ${member.name}`)} variant="outline" size="sm" className="hidden border-white/15 bg-transparent sm:inline-flex">Avisar</Button></div>)}</div>; }
function MembershipsView() { return <><PageTitle eyebrow="Cobros y renovaciones" title="Membresías" accessory={<Button onClick={() => toast.success("Recordatorios enviados")} className="bg-[#c7ff3d] font-black text-black"><Bell /> Enviar recordatorios</Button>} /><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Activas" value="428" change="91% del total" /><MetricCard label="Por vencer" value="23" change="7 días" alert /><MetricCard label="Vencidas" value="19" change="Requieren gestión" alert /></div><article className="mt-5 rounded-[26px] border border-white/10 bg-[#121512] p-5 sm:p-6"><h2 className="mb-3 text-xl font-black">Vencimientos próximos</h2><ExpiringList /></article></>; }
function AdminReports() { return <><PageTitle eyebrow="Rendimiento del negocio" title="Reportes" /><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Tasa de renovación" value="87" suffix="%" change="+4,1%" /><MetricCard label="Ticket promedio" value="$42k" change="Este mes" /><MetricCard label="Altas netas" value="+18" change="Septiembre" /></div><article className="mt-5 rounded-[26px] border border-white/10 bg-[#121512] p-6"><div className="flex justify-between"><div><p className="text-sm text-white/45">Ingresos</p><h2 className="text-2xl font-black">Últimos 6 meses</h2></div><WalletCards className="text-[#c7ff3d]" /></div><ProgressChart /></article></>; }

function PageTitle({ eyebrow, title, accessory }: { eyebrow: string; title: string; accessory?: ReactNode }) { return <div className="mb-6 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-bold uppercase tracking-[0.13em] text-[#c7ff3d]">{eyebrow}</p><h1 className="text-3xl font-black tracking-[-0.045em] sm:text-4xl">{title}</h1></div>{accessory}</div>; }
function MetricCard({ label, value, suffix, change, alert = false }: { label: string; value: string; suffix?: string; change: string; alert?: boolean }) { return <article className="rounded-[22px] border border-white/10 bg-[#121512] p-5"><div className="flex items-center justify-between"><p className="text-sm font-bold text-white/45">{label}</p><ArrowUpRight className={`size-4 ${alert ? "text-amber-400" : "text-[#c7ff3d]"}`} /></div><p className="mt-4 text-3xl font-black tracking-tight">{value}<span className="ml-1 text-lg text-white/40">{suffix}</span></p><p className={`mt-1 text-xs font-bold ${alert ? "text-amber-400" : "text-[#c7ff3d]"}`}>{change}</p></article>; }
function StatMini({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/5 p-3"><p className="text-xs text-white/40">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
function Avatar({ initials, large = false }: { initials: string; large?: boolean }) { return <span className={`grid shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[#dfff91] to-[#91c714] font-black text-black ${large ? "size-20 text-xl" : "size-11 text-sm"}`}>{initials}</span>; }
function Pill({ children }: { children: ReactNode }) { return <span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-bold text-white/55">{children}</span>; }
function MiniBars() { return <div className="flex h-18 items-end gap-1.5" aria-label="Actividad semanal">{[70, 42, 90, 62, 18, 18, 18].map((height, index) => <span key={index} className={`w-2 rounded-full ${index < 4 ? "bg-[#c7ff3d]" : "bg-white/10"}`} style={{ height: `${height}%` }} />)}</div>; }
function ProgressChart() { return <div className="mt-7 overflow-hidden"><svg viewBox="0 0 700 190" className="h-48 w-full" role="img" aria-label="Gráfico ascendente de progreso"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#c7ff3d" stopOpacity=".28"/><stop offset="1" stopColor="#c7ff3d" stopOpacity="0"/></linearGradient></defs>{[40,85,130,175].map((y) => <line key={y} x1="0" x2="700" y1={y} y2={y} stroke="white" strokeOpacity=".08" />)}<path d="M0 154 C70 145 82 132 140 137 S230 116 280 121 S360 92 420 98 S520 67 560 76 S640 35 700 42 L700 190 L0 190Z" fill="url(#area)"/><path d="M0 154 C70 145 82 132 140 137 S230 116 280 121 S360 92 420 98 S520 67 560 76 S640 35 700 42" fill="none" stroke="#c7ff3d" strokeWidth="5" strokeLinecap="round"/><circle cx="700" cy="42" r="7" fill="#c7ff3d" stroke="#121512" strokeWidth="4"/></svg><div className="flex justify-between text-xs text-white/30"><span>Jun</span><span>Jul</span><span>Ago</span><span>Sep</span></div></div>; }
function NavItem({ icon, label, active, onClick }: { icon: ReactNode; label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition-colors [&>svg]:size-5 ${active ? "bg-[#c7ff3d] text-black" : "text-white/45 hover:bg-white/5 hover:text-white"}`}>{icon}<span>{label}</span></button>; }
function MobileNav({ role, view, onView }: { role: Role; view: View; onView: (view: View) => void }) { const items: [View, ReactNode, string][] = role === "member" ? [["home", <Home />, "Inicio"], ["routine", <Dumbbell />, "Rutina"], ["progress", <LineChart />, "Progreso"], ["people", <CircleUserRound />, "Trainer"]] : role === "trainer" ? [["home", <Home />, "Inicio"], ["people", <UsersRound />, "Alumnos"], ["routine", <Dumbbell />, "Rutinas"], ["progress", <LineChart />, "Resultados"]] : [["home", <Home />, "Inicio"], ["people", <UsersRound />, "Socios"], ["routine", <CreditCard />, "Planes"], ["progress", <Activity />, "Reportes"]]; return <nav className="fixed inset-x-3 bottom-3 z-30 flex justify-around rounded-2xl border border-white/10 bg-[#171a17]/95 p-2 shadow-2xl backdrop-blur-xl lg:hidden" aria-label="Navegación móvil">{items.map(([key, icon, label]) => <button key={key} onClick={() => onView(key)} className={`flex min-w-16 flex-col items-center gap-1 rounded-xl px-2 py-1.5 text-[11px] font-bold ${view === key ? "bg-[#c7ff3d] text-black" : "text-white/45"}`}><span className="[&>svg]:size-5">{icon}</span>{label}</button>)}</nav>; }
